# This is a config for E2B sandbox template.
# You can use template ID (brcy9ky1bwp79giwgzwh) or template name (expo-react-native) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("expo-react-native") # Sync sandbox
# sandbox = await AsyncSandbox.create("expo-react-native") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('expo-react-native')

team_id = "1d3e5054-d363-4506-a2a2-a05668749126"
memory_mb = 1_024
cpu_count = 2
start_cmd = "cd /home/user && npm run dev"
dockerfile = "e2b.Dockerfile"
template_name = "expo-react-native"
template_id = "brcy9ky1bwp79giwgzwh"
